# -*- coding: utf-8 -*-
"""Lei do Resfriamento de Newton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4M5Tfg92kspgujyEoHdFaaHuJxn_4nD

# 🌡️ Lei do Resfriamento de Newton — Atividade Guiada

---

## 📘 1. Introdução ao fenômeno físico

A **Lei do Resfriamento de Newton** descreve como a temperatura de um corpo varia ao longo do tempo quando ele troca calor com o ambiente.

A ideia central é simples:

> A taxa de variação da temperatura de um corpo é proporcional à diferença entre sua temperatura e a temperatura do ambiente.

Matematicamente, isso leva a uma solução do tipo exponencial:

[
T(t) = T_{\infty} + (T_0 - T_{\infty}) e^{-kt}
]

Onde:

* (T(t)): temperatura no tempo (t)
* (T_0): temperatura inicial
* (T_{\infty}): temperatura ambiente
* (k): constante de resfriamento


### ▶️ Para resolver o passo-a-passo da atividade execute os blocos abaixo dos campos de explicação:

---

## 🧰 2. Importando as bibliotecas

Agora vamos importar as bibliotecas que serão usadas no código.

* `numpy`: manipulação de arrays e cálculos matemáticos
* `matplotlib.pyplot`: criação de gráficos
* `scipy.optimize.curve_fit`: ajuste de curvas (fit)

---
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

"""
---

## ⏱️ 3. Definindo o vetor de tempo

Aqui definimos os instantes de tempo em que as temperaturas foram medidas.

Neste exemplo:

* Começa em 0 segundos
* Vai até 500 segundos
* Com intervalos de 10 segundos

Caso queira substituir o arange por um array de tempos medidos, use a função np.array com seus pontos experimentais:

```python
np.array([t1, t2, t3, t4, ... tf])
```
Não se esqueça de separar os pontos com vírgula e as casas decimais com ponto.

---
"""

t = np.arange(0, 501, 10)

"""
---

## 🌡️ 4. Inserindo os dados experimentais

Agora você deve inserir os valores medidos no experimento.

⚠️ Substitua os valores abaixo pelos seus próprios dados.

---

"""

T = np.array([
61.7,60,57.8,55.8,54.3,53.2,51.9,51.8,51.2,50.4,
49.8,48.8,47.8,47.2,46.7,46,45.3,44.7,44.1,43.7,
43.3,42.9,42.9,42.1,41.8,41.4,41.1,40.8,40.8,40.3,
39.8,39.8,39.2,38.9,38.8,38.4,38.1,37.8,37.9,37.2,
36.9,36.9,36.7,36.5,36.2,35.9,35.8,35.3,35.1,35,34.8
])

"""



---

## 🌍 5. Definindo temperaturas importantes

Aqui definimos:

* Temperatura inicial (T_0)
* Temperatura ambiente (T_{\infty})

Aqui, T[0] seleciona o primeiro valor do array de temperatura T e T[-1] seleciona o último valor. Você pode substituir T[-1] pelo valor numérico da temperatura ambiente em vez de utilizar o último valor medido para a equação final, mas isto pode prejudicar o ajuste. Faça a mudança no final e veja como fica!

---

"""

T0 = T[0]
T_inf = T[-1]

"""

---

## ⚙️ 6. Definindo o modelo físico

Agora implementamos a equação da Lei de Newton como uma função em Python.

---
"""

def modelo(t, k):
    return T_inf + (T0 - T_inf) * np.exp(-k * t)

"""
---

## 📈 7. Ajuste da curva (fit)

Aqui usamos o método de ajuste para encontrar o melhor valor da constante (k).

---

"""

k_opt, _ = curve_fit(modelo, t, T, p0=[0.01])
k = k_opt[0]

"""---

## 📊 8. Gerando a curva ajustada

Criamos uma curva suave para visualizar melhor o modelo.

---
"""

t_fit = np.linspace(0, 500, 1000)
T_fit = modelo(t_fit, k)

"""
---

## 📉 9. Plotando os resultados

Agora comparamos os dados experimentais com o modelo.

---"""

# Ajusta o tamanho da figura
plt.figure(figsize=(8,5))

# Define plotar em scatter (pontos) o tempo t no eixo x, temperatura T no eixo y, a legenda e a cor (r = vermelho, g = verde, b = azul, entre outras).
plt.scatter(t, T, label='Dados experimentais', color="r")

# Define plotar em linha o tempo ajustado t_fit no eixo x, temperatura ajustada T_fit no eixo y, a legenda e a cor (k = preto).
plt.plot(t_fit, T_fit, label='Ajuste (Lei do resfriamento de Newton)', linewidth=2, color="k")

# Legenda do eixo x
plt.xlabel('Tempo (s)')

# Legenda do eixo y
plt.ylabel('Temperatura (°C)')

# Mostra o gráfico, legenda e as grades de fundo do gráfico. Caso queira salvar a imagem basta apagar o # antes de plt.savefig
plt.legend()
plt.grid()
plt.show()
# plt.savefig("Resfriamento.png", dpi=600)

"""

---

## 🧾 10. Exibindo a equação final

Aqui mostramos a equação ajustada com o valor de (k).

---"""

print("Equação ajustada:")
print(f"T(t) = {T_inf:.2f} + ({T0:.2f} - {T_inf:.2f}) * exp(-{k:.5f} t)")